### ISSUE TITLE
Click rectangle is incorrect

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/fonts#1]
Check out Accelerally:

https://playcanvas.com/project/3489/overview/accelerally

If you run the game, you'll see a 'PLAY' button that you can click to start a game. If you click the lower 50% (roughly) of the play button text, the game does not play (the click handler does not fire). Click from around the midpoint of the height of the text to just above the top of the text will cause the click handler to fire.

Presumably the bounds of the click box are being calculated incorrectly.

**Comment by Nigh7Sh4de** [comment]
@willeastcott I notice that acceleronly seems to be working fine now but I am experiencing the exact same issue in one of my own projects and seeing as this issue report has no commits I am assuming you did something in your project to fix it? My project is engine-only so I dont have a link to the designer project but here is the github repo: https://github.com/nigh7sh4de/tanky

The issue is specifically concerning the Start Game/Play Again button where the bottom half of the text does not seem to function. By stepping through the code it seems that the `my` variable in the `onClick()` method on `font_renderer.js` is not calculated correctly (specifically in the bottom half I get values like `-0.1` and the top half is around `0.0`).

P.S. your link is broken

**Comment by willeastcott** [comment]
I have fixed the link to the game. So it's been a while, but to fix the
selection box, I think I hacked in a fix by changing line 339 of
font_renderer.js to:

```
            tempCursorY = 0; //-yoffset; HACK!!
```

The problem with this hack is that some letters are no longer offset in Y
correctly - for example, check out the leaderboard screen in the game.

On Mon, Mar 16, 2015 at 11:29 AM, Nigh7Sh4de notifications@github.com
wrote:

> @willeastcott https://github.com/willeastcott I notice that acceleronly
> seems to be working fine now but I am experiencing the exact same issue in
> one of my own projects and seeing as this issue report has no commits I am
> assuming you did something in your project to fix it? My project is
> engine-only so I dont have a link to the designer project but here is the
> github repo: https://github.com/nigh7sh4de/tanky
> 
> The issue is specifically concerning the Start Game/Play Again button
> where the bottom half of the text does not seem to function. By stepping
> through the code it seems that the my variable in the onClick() method on
> font_renderer.js is not calculated correctly (specifically in the bottom
> half I get values like -0.1 and the top half is around 0.0).
> 
> P.S. your link is broken
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/playcanvas/fonts/issues/1#issuecomment-81855924.

## 

Will Eastcott (@willeastcott https://twitter.com/willeastcott)
CEO, PlayCanvas Ltd

## http://playcanvas.com

It's not just me who thinks we're great:
Technical Innovation Award Nomination
http://www.developawards.com/finalists2
Top 100 Game Tech Company
http://www.develop-online.net/news/develop-100-27-uk-games-hardware-and-tools-named-in-tech-list/0194913
Featured by Apple at WWDC
https://developer.apple.com/videos/wwdc/2014/#509
